packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.6'
  - '@better-auth/drizzle-adapter@1.7.6'
  - '@better-auth/kysely-adapter@1.7.6'
  - '@better-auth/memory-adapter@1.7.6'
  - '@better-auth/mongo-adapter@1.7.6'
  - '@better-auth/prisma-adapter@1.7.6'
  - '@better-auth/telemetry@1.7.6'
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - better-auth@1.7.6
  - vitest@5.0.2
  - auth@1.7.6
  - '@tanstack/query-core@5.103.3'
  - '@tanstack/react-query@5.103.3'
